//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.10 at 11:47:16 PM IST 
//


package pc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "attribute"
})
@XmlRootElement(name = "CONNECTIONREFERENCE")
public class CONNECTIONREFERENCE {

    @XmlAttribute(name = "CNXREFNAME", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String cnxrefname;
    @XmlAttribute(name = "CONNECTIONTYPE", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String connectiontype;
    @XmlAttribute(name = "CONNECTIONSUBTYPE", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String connectionsubtype;
    @XmlAttribute(name = "CONNECTIONNUMBER", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String connectionnumber;
    @XmlAttribute(name = "CONNECTIONNAME", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String connectionname;
    @XmlAttribute(name = "PARTITIONNAME")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String partitionname;
    @XmlAttribute(name = "VARIABLE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String variable;
    @XmlAttribute(name = "COMPONENTVERSION")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String componentversion;
    @XmlElement(name = "ATTRIBUTE")
    protected List<ATTRIBUTE> attribute;

    /**
     * Gets the value of the cnxrefname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCNXREFNAME() {
        return cnxrefname;
    }

    /**
     * Sets the value of the cnxrefname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCNXREFNAME(String value) {
        this.cnxrefname = value;
    }

    /**
     * Gets the value of the connectiontype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONNECTIONTYPE() {
        return connectiontype;
    }

    /**
     * Sets the value of the connectiontype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONNECTIONTYPE(String value) {
        this.connectiontype = value;
    }

    /**
     * Gets the value of the connectionsubtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONNECTIONSUBTYPE() {
        return connectionsubtype;
    }

    /**
     * Sets the value of the connectionsubtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONNECTIONSUBTYPE(String value) {
        this.connectionsubtype = value;
    }

    /**
     * Gets the value of the connectionnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONNECTIONNUMBER() {
        return connectionnumber;
    }

    /**
     * Sets the value of the connectionnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONNECTIONNUMBER(String value) {
        this.connectionnumber = value;
    }

    /**
     * Gets the value of the connectionname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONNECTIONNAME() {
        return connectionname;
    }

    /**
     * Sets the value of the connectionname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONNECTIONNAME(String value) {
        this.connectionname = value;
    }

    /**
     * Gets the value of the partitionname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPARTITIONNAME() {
        return partitionname;
    }

    /**
     * Sets the value of the partitionname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPARTITIONNAME(String value) {
        this.partitionname = value;
    }

    /**
     * Gets the value of the variable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVARIABLE() {
        return variable;
    }

    /**
     * Sets the value of the variable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVARIABLE(String value) {
        this.variable = value;
    }

    /**
     * Gets the value of the componentversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOMPONENTVERSION() {
        return componentversion;
    }

    /**
     * Sets the value of the componentversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOMPONENTVERSION(String value) {
        this.componentversion = value;
    }

    /**
     * Gets the value of the attribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getATTRIBUTE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ATTRIBUTE }
     * 
     * 
     */
    public List<ATTRIBUTE> getATTRIBUTE() {
        if (attribute == null) {
            attribute = new ArrayList<ATTRIBUTE>();
        }
        return this.attribute;
    }

}
