//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.10 at 11:47:16 PM IST 
//


package pc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "CONWFRUNINFO")
public class CONWFRUNINFO {

    @XmlAttribute(name = "CONWFRUNINSTNAME")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String conwfruninstname;
    @XmlAttribute(name = "CONWFPARAMFILE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String conwfparamfile;

    /**
     * Gets the value of the conwfruninstname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONWFRUNINSTNAME() {
        return conwfruninstname;
    }

    /**
     * Sets the value of the conwfruninstname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONWFRUNINSTNAME(String value) {
        this.conwfruninstname = value;
    }

    /**
     * Gets the value of the conwfparamfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONWFPARAMFILE() {
        return conwfparamfile;
    }

    /**
     * Sets the value of the conwfparamfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONWFPARAMFILE(String value) {
        this.conwfparamfile = value;
    }

}
