//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.10 at 11:47:16 PM IST 
//


package pc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dailyfrequency",
    "repeat"
})
@XmlRootElement(name = "CUSTOM")
public class CUSTOM {

    @XmlElement(name = "DAILYFREQUENCY", required = true)
    protected DAILYFREQUENCY dailyfrequency;
    @XmlElement(name = "REPEAT")
    protected REPEAT repeat;

    /**
     * Gets the value of the dailyfrequency property.
     * 
     * @return
     *     possible object is
     *     {@link DAILYFREQUENCY }
     *     
     */
    public DAILYFREQUENCY getDAILYFREQUENCY() {
        return dailyfrequency;
    }

    /**
     * Sets the value of the dailyfrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link DAILYFREQUENCY }
     *     
     */
    public void setDAILYFREQUENCY(DAILYFREQUENCY value) {
        this.dailyfrequency = value;
    }

    /**
     * Gets the value of the repeat property.
     * 
     * @return
     *     possible object is
     *     {@link REPEAT }
     *     
     */
    public REPEAT getREPEAT() {
        return repeat;
    }

    /**
     * Sets the value of the repeat property.
     * 
     * @param value
     *     allowed object is
     *     {@link REPEAT }
     *     
     */
    public void setREPEAT(REPEAT value) {
        this.repeat = value;
    }

}
