//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.10 at 11:47:16 PM IST 
//


package pc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "DAILYFREQUENCY")
public class DAILYFREQUENCY {

    @XmlAttribute(name = "HOURS")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String hours;
    @XmlAttribute(name = "MINUTES")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String minutes;
    @XmlAttribute(name = "RUNONCE")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String runonce;

    /**
     * Gets the value of the hours property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHOURS() {
        return hours;
    }

    /**
     * Sets the value of the hours property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHOURS(String value) {
        this.hours = value;
    }

    /**
     * Gets the value of the minutes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMINUTES() {
        return minutes;
    }

    /**
     * Sets the value of the minutes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMINUTES(String value) {
        this.minutes = value;
    }

    /**
     * Gets the value of the runonce property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRUNONCE() {
        return runonce;
    }

    /**
     * Sets the value of the runonce property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRUNONCE(String value) {
        this.runonce = value;
    }

}
