//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.10 at 11:47:16 PM IST 
//


package pc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sapfunction",
    "sapstructure",
    "sapprogram",
    "sapoutputportOrSAPVARIABLEOrSAPPROGRAMFLOWOBJECT"
})
@XmlRootElement(name = "ERPINFO")
public class ERPINFO {

    @XmlElement(name = "SAPFUNCTION")
    protected List<SAPFUNCTION> sapfunction;
    @XmlElement(name = "SAPSTRUCTURE")
    protected List<SAPSTRUCTURE> sapstructure;
    @XmlElement(name = "SAPPROGRAM")
    protected List<SAPPROGRAM> sapprogram;
    @XmlElements({
        @XmlElement(name = "SAPOUTPUTPORT", type = SAPOUTPUTPORT.class),
        @XmlElement(name = "SAPVARIABLE", type = SAPVARIABLE.class),
        @XmlElement(name = "SAPPROGRAMFLOWOBJECT", type = SAPPROGRAMFLOWOBJECT.class)
    })
    protected List<Object> sapoutputportOrSAPVARIABLEOrSAPPROGRAMFLOWOBJECT;

    /**
     * Gets the value of the sapfunction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sapfunction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSAPFUNCTION().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SAPFUNCTION }
     * 
     * 
     */
    public List<SAPFUNCTION> getSAPFUNCTION() {
        if (sapfunction == null) {
            sapfunction = new ArrayList<SAPFUNCTION>();
        }
        return this.sapfunction;
    }

    /**
     * Gets the value of the sapstructure property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sapstructure property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSAPSTRUCTURE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SAPSTRUCTURE }
     * 
     * 
     */
    public List<SAPSTRUCTURE> getSAPSTRUCTURE() {
        if (sapstructure == null) {
            sapstructure = new ArrayList<SAPSTRUCTURE>();
        }
        return this.sapstructure;
    }

    /**
     * Gets the value of the sapprogram property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sapprogram property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSAPPROGRAM().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SAPPROGRAM }
     * 
     * 
     */
    public List<SAPPROGRAM> getSAPPROGRAM() {
        if (sapprogram == null) {
            sapprogram = new ArrayList<SAPPROGRAM>();
        }
        return this.sapprogram;
    }

    /**
     * Gets the value of the sapoutputportOrSAPVARIABLEOrSAPPROGRAMFLOWOBJECT property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sapoutputportOrSAPVARIABLEOrSAPPROGRAMFLOWOBJECT property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSAPOUTPUTPORTOrSAPVARIABLEOrSAPPROGRAMFLOWOBJECT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SAPOUTPUTPORT }
     * {@link SAPVARIABLE }
     * {@link SAPPROGRAMFLOWOBJECT }
     * 
     * 
     */
    public List<Object> getSAPOUTPUTPORTOrSAPVARIABLEOrSAPPROGRAMFLOWOBJECT() {
        if (sapoutputportOrSAPVARIABLEOrSAPPROGRAMFLOWOBJECT == null) {
            sapoutputportOrSAPVARIABLEOrSAPPROGRAMFLOWOBJECT = new ArrayList<Object>();
        }
        return this.sapoutputportOrSAPVARIABLEOrSAPPROGRAMFLOWOBJECT;
    }

}
