//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.10 at 11:47:16 PM IST 
//


package pc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "seblsrcinfo"
})
@XmlRootElement(name = "ERPSRCINFO")
public class ERPSRCINFO {

    @XmlElement(name = "SEBLSRCINFO")
    protected SEBLSRCINFO seblsrcinfo;

    /**
     * Gets the value of the seblsrcinfo property.
     * 
     * @return
     *     possible object is
     *     {@link SEBLSRCINFO }
     *     
     */
    public SEBLSRCINFO getSEBLSRCINFO() {
        return seblsrcinfo;
    }

    /**
     * Sets the value of the seblsrcinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SEBLSRCINFO }
     *     
     */
    public void setSEBLSRCINFO(SEBLSRCINFO value) {
        this.seblsrcinfo = value;
    }

}
