//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.10 at 11:47:16 PM IST 
//


package pc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "macroargument",
    "macrodependency"
})
@XmlRootElement(name = "EXPRMACRO")
public class EXPRMACRO {

    @XmlAttribute(name = "NAME", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "DESCRIPTION")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String description;
    @XmlAttribute(name = "OBJECTVERSION")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String objectversion;
    @XmlAttribute(name = "PROTOTYPE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String prototype;
    @XmlAttribute(name = "EXPRESSION", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String expression;
    @XmlAttribute(name = "MACROTYPE")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String macrotype;
    @XmlAttribute(name = "RETURNTYPE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String returntype;
    @XmlAttribute(name = "VERSIONNUMBER")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String versionnumber;
    @XmlElement(name = "MACROARGUMENT")
    protected List<MACROARGUMENT> macroargument;
    @XmlElement(name = "MACRODEPENDENCY")
    protected List<MACRODEPENDENCY> macrodependency;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCRIPTION() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCRIPTION(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the objectversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOBJECTVERSION() {
        return objectversion;
    }

    /**
     * Sets the value of the objectversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOBJECTVERSION(String value) {
        this.objectversion = value;
    }

    /**
     * Gets the value of the prototype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPROTOTYPE() {
        return prototype;
    }

    /**
     * Sets the value of the prototype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPROTOTYPE(String value) {
        this.prototype = value;
    }

    /**
     * Gets the value of the expression property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXPRESSION() {
        return expression;
    }

    /**
     * Sets the value of the expression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXPRESSION(String value) {
        this.expression = value;
    }

    /**
     * Gets the value of the macrotype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMACROTYPE() {
        return macrotype;
    }

    /**
     * Sets the value of the macrotype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMACROTYPE(String value) {
        this.macrotype = value;
    }

    /**
     * Gets the value of the returntype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRETURNTYPE() {
        return returntype;
    }

    /**
     * Sets the value of the returntype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRETURNTYPE(String value) {
        this.returntype = value;
    }

    /**
     * Gets the value of the versionnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVERSIONNUMBER() {
        return versionnumber;
    }

    /**
     * Sets the value of the versionnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVERSIONNUMBER(String value) {
        this.versionnumber = value;
    }

    /**
     * Gets the value of the macroargument property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the macroargument property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMACROARGUMENT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MACROARGUMENT }
     * 
     * 
     */
    public List<MACROARGUMENT> getMACROARGUMENT() {
        if (macroargument == null) {
            macroargument = new ArrayList<MACROARGUMENT>();
        }
        return this.macroargument;
    }

    /**
     * Gets the value of the macrodependency property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the macrodependency property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMACRODEPENDENCY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MACRODEPENDENCY }
     * 
     * 
     */
    public List<MACRODEPENDENCY> getMACRODEPENDENCY() {
        if (macrodependency == null) {
            macrodependency = new ArrayList<MACRODEPENDENCY>();
        }
        return this.macrodependency;
    }

}
