//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.10 at 11:47:16 PM IST 
//


package pc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "FIELDDEPENDENCY")
public class FIELDDEPENDENCY {

    @XmlAttribute(name = "INPUTFIELD", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String inputfield;
    @XmlAttribute(name = "OUTPUTFIELD", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String outputfield;

    /**
     * Gets the value of the inputfield property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINPUTFIELD() {
        return inputfield;
    }

    /**
     * Sets the value of the inputfield property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINPUTFIELD(String value) {
        this.inputfield = value;
    }

    /**
     * Gets the value of the outputfield property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOUTPUTFIELD() {
        return outputfield;
    }

    /**
     * Sets the value of the outputfield property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOUTPUTFIELD(String value) {
        this.outputfield = value;
    }

}
