//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.10 at 11:47:16 PM IST 
//


package pc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "FLATFILE")
public class FLATFILE {

    @XmlAttribute(name = "FILENAME")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String filename;
    @XmlAttribute(name = "FILETYPE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String filetype;
    @XmlAttribute(name = "DELIMITED")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String delimited;
    @XmlAttribute(name = "DELIMITERS")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String delimiters;
    @XmlAttribute(name = "ROWDELIMITER")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String rowdelimiter;
    @XmlAttribute(name = "DELIMITERS_IN_BINARY")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String delimitersinbinary;
    @XmlAttribute(name = "QUOTE_CHARACTER")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String quotecharacter;
    @XmlAttribute(name = "NULL_CHARACTER")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String nullcharacter;
    @XmlAttribute(name = "NULLCHARTYPE")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String nullchartype;
    @XmlAttribute(name = "STAGEFILEREINIT")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String stagefilereinit;
    @XmlAttribute(name = "STAGEFILEPERSIST")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String stagefilepersist;
    @XmlAttribute(name = "REPEATABLE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String repeatable;
    @XmlAttribute(name = "CONSECDELIMITERSASONE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String consecdelimitersasone;
    @XmlAttribute(name = "STRIPTRAILINGBLANKS")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String striptrailingblanks;
    @XmlAttribute(name = "PADBYTES")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String padbytes;
    @XmlAttribute(name = "SKIPLEADINGBYTES")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String skipleadingbytes;
    @XmlAttribute(name = "SKIPTRAILINGBYTES")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String skiptrailingbytes;
    @XmlAttribute(name = "LINESEQUENTIAL")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String linesequential;
    @XmlAttribute(name = "KEEPESCAPECHAR")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String keepescapechar;
    @XmlAttribute(name = "SHIFTSENSITIVEDATA")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String shiftsensitivedata;
    @XmlAttribute(name = "ESCAPE_CHARACTER")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String escapecharacter;
    @XmlAttribute(name = "SKIPROWS")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String skiprows;
    @XmlAttribute(name = "CODEPAGE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String codepage;

    /**
     * Gets the value of the filename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFILENAME() {
        return filename;
    }

    /**
     * Sets the value of the filename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFILENAME(String value) {
        this.filename = value;
    }

    /**
     * Gets the value of the filetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFILETYPE() {
        return filetype;
    }

    /**
     * Sets the value of the filetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFILETYPE(String value) {
        this.filetype = value;
    }

    /**
     * Gets the value of the delimited property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDELIMITED() {
        return delimited;
    }

    /**
     * Sets the value of the delimited property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDELIMITED(String value) {
        this.delimited = value;
    }

    /**
     * Gets the value of the delimiters property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDELIMITERS() {
        return delimiters;
    }

    /**
     * Sets the value of the delimiters property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDELIMITERS(String value) {
        this.delimiters = value;
    }

    /**
     * Gets the value of the rowdelimiter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getROWDELIMITER() {
        return rowdelimiter;
    }

    /**
     * Sets the value of the rowdelimiter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setROWDELIMITER(String value) {
        this.rowdelimiter = value;
    }

    /**
     * Gets the value of the delimitersinbinary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDELIMITERSINBINARY() {
        return delimitersinbinary;
    }

    /**
     * Sets the value of the delimitersinbinary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDELIMITERSINBINARY(String value) {
        this.delimitersinbinary = value;
    }

    /**
     * Gets the value of the quotecharacter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQUOTECHARACTER() {
        return quotecharacter;
    }

    /**
     * Sets the value of the quotecharacter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQUOTECHARACTER(String value) {
        this.quotecharacter = value;
    }

    /**
     * Gets the value of the nullcharacter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNULLCHARACTER() {
        return nullcharacter;
    }

    /**
     * Sets the value of the nullcharacter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNULLCHARACTER(String value) {
        this.nullcharacter = value;
    }

    /**
     * Gets the value of the nullchartype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNULLCHARTYPE() {
        return nullchartype;
    }

    /**
     * Sets the value of the nullchartype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNULLCHARTYPE(String value) {
        this.nullchartype = value;
    }

    /**
     * Gets the value of the stagefilereinit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTAGEFILEREINIT() {
        return stagefilereinit;
    }

    /**
     * Sets the value of the stagefilereinit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTAGEFILEREINIT(String value) {
        this.stagefilereinit = value;
    }

    /**
     * Gets the value of the stagefilepersist property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTAGEFILEPERSIST() {
        return stagefilepersist;
    }

    /**
     * Sets the value of the stagefilepersist property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTAGEFILEPERSIST(String value) {
        this.stagefilepersist = value;
    }

    /**
     * Gets the value of the repeatable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREPEATABLE() {
        return repeatable;
    }

    /**
     * Sets the value of the repeatable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREPEATABLE(String value) {
        this.repeatable = value;
    }

    /**
     * Gets the value of the consecdelimitersasone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONSECDELIMITERSASONE() {
        return consecdelimitersasone;
    }

    /**
     * Sets the value of the consecdelimitersasone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONSECDELIMITERSASONE(String value) {
        this.consecdelimitersasone = value;
    }

    /**
     * Gets the value of the striptrailingblanks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTRIPTRAILINGBLANKS() {
        return striptrailingblanks;
    }

    /**
     * Sets the value of the striptrailingblanks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTRIPTRAILINGBLANKS(String value) {
        this.striptrailingblanks = value;
    }

    /**
     * Gets the value of the padbytes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPADBYTES() {
        return padbytes;
    }

    /**
     * Sets the value of the padbytes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPADBYTES(String value) {
        this.padbytes = value;
    }

    /**
     * Gets the value of the skipleadingbytes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSKIPLEADINGBYTES() {
        return skipleadingbytes;
    }

    /**
     * Sets the value of the skipleadingbytes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSKIPLEADINGBYTES(String value) {
        this.skipleadingbytes = value;
    }

    /**
     * Gets the value of the skiptrailingbytes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSKIPTRAILINGBYTES() {
        return skiptrailingbytes;
    }

    /**
     * Sets the value of the skiptrailingbytes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSKIPTRAILINGBYTES(String value) {
        this.skiptrailingbytes = value;
    }

    /**
     * Gets the value of the linesequential property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLINESEQUENTIAL() {
        return linesequential;
    }

    /**
     * Sets the value of the linesequential property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLINESEQUENTIAL(String value) {
        this.linesequential = value;
    }

    /**
     * Gets the value of the keepescapechar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKEEPESCAPECHAR() {
        return keepescapechar;
    }

    /**
     * Sets the value of the keepescapechar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKEEPESCAPECHAR(String value) {
        this.keepescapechar = value;
    }

    /**
     * Gets the value of the shiftsensitivedata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSHIFTSENSITIVEDATA() {
        return shiftsensitivedata;
    }

    /**
     * Sets the value of the shiftsensitivedata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSHIFTSENSITIVEDATA(String value) {
        this.shiftsensitivedata = value;
    }

    /**
     * Gets the value of the escapecharacter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getESCAPECHARACTER() {
        return escapecharacter;
    }

    /**
     * Sets the value of the escapecharacter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setESCAPECHARACTER(String value) {
        this.escapecharacter = value;
    }

    /**
     * Gets the value of the skiprows property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSKIPROWS() {
        return skiprows;
    }

    /**
     * Sets the value of the skiprows property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSKIPROWS(String value) {
        this.skiprows = value;
    }

    /**
     * Gets the value of the codepage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODEPAGE() {
        return codepage;
    }

    /**
     * Sets the value of the codepage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODEPAGE(String value) {
        this.codepage = value;
    }

}
