//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.10 at 11:47:16 PM IST 
//


package pc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "KEYRANGE")
public class KEYRANGE {

    @XmlAttribute(name = "NAME", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "STARTRANGE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String startrange;
    @XmlAttribute(name = "ENDRANGE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String endrange;
    @XmlAttribute(name = "SRCINSTANCENAME")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String srcinstancename;
    @XmlAttribute(name = "GROUP")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String group;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the startrange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTARTRANGE() {
        return startrange;
    }

    /**
     * Sets the value of the startrange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTARTRANGE(String value) {
        this.startrange = value;
    }

    /**
     * Gets the value of the endrange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getENDRANGE() {
        return endrange;
    }

    /**
     * Sets the value of the endrange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setENDRANGE(String value) {
        this.endrange = value;
    }

    /**
     * Gets the value of the srcinstancename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSRCINSTANCENAME() {
        return srcinstancename;
    }

    /**
     * Sets the value of the srcinstancename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSRCINSTANCENAME(String value) {
        this.srcinstancename = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGROUP() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGROUP(String value) {
        this.group = value;
    }

}
