//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.10 at 11:47:16 PM IST 
//


package pc;
import dag.*;
import constant.*;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transformation",
    "instance",
    "connector",
    "mapdependency",
    "targetloadorder",
    "mappingvariable",
    "erpinfo",
    "metadataextension"
})
@XmlRootElement(name = "MAPPING")
public class MAPPING {

    @XmlAttribute(name = "NAME", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "DESCRIPTION")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String description;
    @XmlAttribute(name = "OBJECTVERSION")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String objectversion;
    @XmlAttribute(name = "ISVALID")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String isvalid;
    @XmlAttribute(name = "ISPROFILEMAPPING")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String isprofilemapping;
    @XmlAttribute(name = "VERSIONNUMBER")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String versionnumber;
    @XmlAttribute(name = "CRCVALUE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String crcvalue;
    @XmlElement(name = "TRANSFORMATION")
    protected List<TRANSFORMATION> transformation;
    @XmlElement(name = "INSTANCE")
    protected List<INSTANCE> instance;
    @XmlElement(name = "CONNECTOR")
    protected List<CONNECTOR> connector;
    @XmlElement(name = "MAPDEPENDENCY")
    protected List<MAPDEPENDENCY> mapdependency;
    @XmlElement(name = "TARGETLOADORDER")
    protected List<TARGETLOADORDER> targetloadorder;
    @XmlElement(name = "MAPPINGVARIABLE")
    protected List<MAPPINGVARIABLE> mappingvariable;
    @XmlElement(name = "ERPINFO")
    protected List<ERPINFO> erpinfo;
    @XmlElement(name = "METADATAEXTENSION")
    protected List<METADATAEXTENSION> metadataextension;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCRIPTION() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCRIPTION(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the objectversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOBJECTVERSION() {
        return objectversion;
    }

    /**
     * Sets the value of the objectversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOBJECTVERSION(String value) {
        this.objectversion = value;
    }

    /**
     * Gets the value of the isvalid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISVALID() {
        return isvalid;
    }

    /**
     * Sets the value of the isvalid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISVALID(String value) {
        this.isvalid = value;
    }

    /**
     * Gets the value of the isprofilemapping property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISPROFILEMAPPING() {
        return isprofilemapping;
    }

    /**
     * Sets the value of the isprofilemapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISPROFILEMAPPING(String value) {
        this.isprofilemapping = value;
    }

    /**
     * Gets the value of the versionnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVERSIONNUMBER() {
        return versionnumber;
    }

    /**
     * Sets the value of the versionnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVERSIONNUMBER(String value) {
        this.versionnumber = value;
    }

    /**
     * Gets the value of the crcvalue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRCVALUE() {
        return crcvalue;
    }

    /**
     * Sets the value of the crcvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRCVALUE(String value) {
        this.crcvalue = value;
    }

    /**
     * Gets the value of the transformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTRANSFORMATION().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRANSFORMATION }
     * 
     * 
     */
    public List<TRANSFORMATION> getTRANSFORMATION() {
        if (transformation == null) {
            transformation = new ArrayList<TRANSFORMATION>();
        }
        return this.transformation;
    }

    /**
     * Gets the value of the instance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getINSTANCE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link INSTANCE }
     * 
     * 
     */
    public List<INSTANCE> getINSTANCE() {
        if (instance == null) {
            instance = new ArrayList<INSTANCE>();
        }
        return this.instance;
    }

    /**
     * Gets the value of the connector property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the connector property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCONNECTOR().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CONNECTOR }
     * 
     * 
     */
    public List<CONNECTOR> getCONNECTOR() {
        if (connector == null) {
            connector = new ArrayList<CONNECTOR>();
        }
        return this.connector;
    }

    public List<CONNECTOR> getConnectorByInstance(String name){
        if (connector == null) {
            connector = new ArrayList<CONNECTOR>();
        }
        List<CONNECTOR> inst = new ArrayList<CONNECTOR>();
        for(CONNECTOR c:connector) {
            if(c.getTOINSTANCE().equals(name) || c.getFROMINSTANCE().equals(name)){
                inst.add(c);
            }
        }
        return inst;
    }
    public List<String> getAllConnectedInputs(String to){
        if (connector == null) {
            connector = new ArrayList<CONNECTOR>();
        }
        List<String> inst = new ArrayList<String>();
        for(CONNECTOR c:connector) {
            if(c.getTOINSTANCE().equals(to) ){
                inst.add(c.getTOFIELD());
            }
        }
        return inst;
    }
    public List<String> getAllConnectedOutputs(String from){
        if (connector == null) {
            connector = new ArrayList<CONNECTOR>();
        }
        List<String> inst = new ArrayList<String>();
        for(CONNECTOR c:connector) {
            if(c.getFROMINSTANCE().equals(from) ){
                inst.add(c.getFROMFIELD());
            }
        }
        return inst;
    }

    
    /**
     * Gets the value of the mapdependency property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mapdependency property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMAPDEPENDENCY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MAPDEPENDENCY }
     * 
     * 
     */
    public List<MAPDEPENDENCY> getMAPDEPENDENCY() {
        if (mapdependency == null) {
            mapdependency = new ArrayList<MAPDEPENDENCY>();
        }
        return this.mapdependency;
    }

    /**
     * Gets the value of the targetloadorder property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the targetloadorder property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTARGETLOADORDER().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TARGETLOADORDER }
     * 
     * 
     */
    public List<TARGETLOADORDER> getTARGETLOADORDER() {
        if (targetloadorder == null) {
            targetloadorder = new ArrayList<TARGETLOADORDER>();
        }
        return this.targetloadorder;
    }

    /**
     * Gets the value of the mappingvariable property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mappingvariable property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMAPPINGVARIABLE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MAPPINGVARIABLE }
     * 
     * 
     */
    public List<MAPPINGVARIABLE> getMAPPINGVARIABLE() {
        if (mappingvariable == null) {
            mappingvariable = new ArrayList<MAPPINGVARIABLE>();
        }
        return this.mappingvariable;
    }

    /**
     * Gets the value of the erpinfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the erpinfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getERPINFO().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ERPINFO }
     * 
     * 
     */
    public List<ERPINFO> getERPINFO() {
        if (erpinfo == null) {
            erpinfo = new ArrayList<ERPINFO>();
        }
        return this.erpinfo;
    }

    /**
     * Gets the value of the metadataextension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metadataextension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMETADATAEXTENSION().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link METADATAEXTENSION }
     * 
     * 
     */
    public List<METADATAEXTENSION> getMETADATAEXTENSION() {
        if (metadataextension == null) {
            metadataextension = new ArrayList<METADATAEXTENSION>();
        }
        return this.metadataextension;
    }

}
