//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.10 at 11:47:16 PM IST 
//


package pc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "SEBLMVLINK")
public class SEBLMVLINK {

    @XmlAttribute(name = "BCNAME", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String bcname;
    @XmlAttribute(name = "MVLINK", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String mvlink;
    @XmlAttribute(name = "DESTLINK", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String destlink;
    @XmlAttribute(name = "DESTBC", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String destbc;
    @XmlAttribute(name = "SRCFIELD", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String srcfield;
    @XmlAttribute(name = "PRIMARYID")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String primaryid;

    /**
     * Gets the value of the bcname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBCNAME() {
        return bcname;
    }

    /**
     * Sets the value of the bcname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBCNAME(String value) {
        this.bcname = value;
    }

    /**
     * Gets the value of the mvlink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMVLINK() {
        return mvlink;
    }

    /**
     * Sets the value of the mvlink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMVLINK(String value) {
        this.mvlink = value;
    }

    /**
     * Gets the value of the destlink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESTLINK() {
        return destlink;
    }

    /**
     * Sets the value of the destlink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESTLINK(String value) {
        this.destlink = value;
    }

    /**
     * Gets the value of the destbc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESTBC() {
        return destbc;
    }

    /**
     * Sets the value of the destbc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESTBC(String value) {
        this.destbc = value;
    }

    /**
     * Gets the value of the srcfield property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSRCFIELD() {
        return srcfield;
    }

    /**
     * Sets the value of the srcfield property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSRCFIELD(String value) {
        this.srcfield = value;
    }

    /**
     * Gets the value of the primaryid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRIMARYID() {
        return primaryid;
    }

    /**
     * Sets the value of the primaryid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRIMARYID(String value) {
        this.primaryid = value;
    }

}
