//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.10 at 11:47:16 PM IST 
//


package pc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "SEBLMVLINKREL")
public class SEBLMVLINKREL {

    @XmlAttribute(name = "SRCMVLINK")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String srcmvlink;
    @XmlAttribute(name = "DESTMVLINK")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String destmvlink;
    @XmlAttribute(name = "FIELD", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String field;

    /**
     * Gets the value of the srcmvlink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSRCMVLINK() {
        return srcmvlink;
    }

    /**
     * Sets the value of the srcmvlink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSRCMVLINK(String value) {
        this.srcmvlink = value;
    }

    /**
     * Gets the value of the destmvlink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESTMVLINK() {
        return destmvlink;
    }

    /**
     * Sets the value of the destmvlink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESTMVLINK(String value) {
        this.destmvlink = value;
    }

    /**
     * Gets the value of the field property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIELD() {
        return field;
    }

    /**
     * Sets the value of the field property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIELD(String value) {
        this.field = value;
    }

}
