//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.10 at 11:47:16 PM IST 
//


package pc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "attribute",
    "workflowvariable",
    "valuepair",
    "configreference",
    "sessioncomponent",
    "sessionextension",
    "resourcereferenceOrTRANSFORMRESOURCEREF"
})
@XmlRootElement(name = "TASKINSTANCE")
public class TASKINSTANCE {

    @XmlAttribute(name = "NAME", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "DESCRIPTION")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String description;
    @XmlAttribute(name = "TASKTYPE", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String tasktype;
    @XmlAttribute(name = "TASKNAME", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String taskname;
    @XmlAttribute(name = "ISENABLED")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String isenabled;
    @XmlAttribute(name = "REUSABLE", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String reusable;
    @XmlAttribute(name = "TREAT_INPUTLINK_AS_AND")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String treatinputlinkasand;
    @XmlAttribute(name = "FAIL_PARENT_IF_INSTANCE_FAILS")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String failparentifinstancefails;
    @XmlAttribute(name = "FAIL_PARENT_IF_INSTANCE_DID_NOT_RUN")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String failparentifinstancedidnotrun;
    @XmlAttribute(name = "SERVER_OVERRIDE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String serveroverride;
    @XmlElement(name = "ATTRIBUTE")
    protected List<ATTRIBUTE> attribute;
    @XmlElement(name = "WORKFLOWVARIABLE")
    protected List<WORKFLOWVARIABLE> workflowvariable;
    @XmlElement(name = "VALUEPAIR")
    protected List<VALUEPAIR> valuepair;
    @XmlElement(name = "CONFIGREFERENCE")
    protected CONFIGREFERENCE configreference;
    @XmlElement(name = "SESSIONCOMPONENT")
    protected List<SESSIONCOMPONENT> sessioncomponent;
    @XmlElement(name = "SESSIONEXTENSION")
    protected List<SESSIONEXTENSION> sessionextension;
    @XmlElements({
        @XmlElement(name = "RESOURCEREFERENCE", type = RESOURCEREFERENCE.class),
        @XmlElement(name = "TRANSFORMRESOURCEREF", type = TRANSFORMRESOURCEREF.class)
    })
    protected List<Object> resourcereferenceOrTRANSFORMRESOURCEREF;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCRIPTION() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCRIPTION(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the tasktype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTASKTYPE() {
        return tasktype;
    }

    /**
     * Sets the value of the tasktype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTASKTYPE(String value) {
        this.tasktype = value;
    }

    /**
     * Gets the value of the taskname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTASKNAME() {
        return taskname;
    }

    /**
     * Sets the value of the taskname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTASKNAME(String value) {
        this.taskname = value;
    }

    /**
     * Gets the value of the isenabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISENABLED() {
        return isenabled;
    }

    /**
     * Sets the value of the isenabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISENABLED(String value) {
        this.isenabled = value;
    }

    /**
     * Gets the value of the reusable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREUSABLE() {
        return reusable;
    }

    /**
     * Sets the value of the reusable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREUSABLE(String value) {
        this.reusable = value;
    }

    /**
     * Gets the value of the treatinputlinkasand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTREATINPUTLINKASAND() {
        return treatinputlinkasand;
    }

    /**
     * Sets the value of the treatinputlinkasand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTREATINPUTLINKASAND(String value) {
        this.treatinputlinkasand = value;
    }

    /**
     * Gets the value of the failparentifinstancefails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFAILPARENTIFINSTANCEFAILS() {
        return failparentifinstancefails;
    }

    /**
     * Sets the value of the failparentifinstancefails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFAILPARENTIFINSTANCEFAILS(String value) {
        this.failparentifinstancefails = value;
    }

    /**
     * Gets the value of the failparentifinstancedidnotrun property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFAILPARENTIFINSTANCEDIDNOTRUN() {
        return failparentifinstancedidnotrun;
    }

    /**
     * Sets the value of the failparentifinstancedidnotrun property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFAILPARENTIFINSTANCEDIDNOTRUN(String value) {
        this.failparentifinstancedidnotrun = value;
    }

    /**
     * Gets the value of the serveroverride property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSERVEROVERRIDE() {
        return serveroverride;
    }

    /**
     * Sets the value of the serveroverride property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSERVEROVERRIDE(String value) {
        this.serveroverride = value;
    }

    /**
     * Gets the value of the attribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getATTRIBUTE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ATTRIBUTE }
     * 
     * 
     */
    public List<ATTRIBUTE> getATTRIBUTE() {
        if (attribute == null) {
            attribute = new ArrayList<ATTRIBUTE>();
        }
        return this.attribute;
    }

    /**
     * Gets the value of the workflowvariable property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the workflowvariable property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWORKFLOWVARIABLE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WORKFLOWVARIABLE }
     * 
     * 
     */
    public List<WORKFLOWVARIABLE> getWORKFLOWVARIABLE() {
        if (workflowvariable == null) {
            workflowvariable = new ArrayList<WORKFLOWVARIABLE>();
        }
        return this.workflowvariable;
    }

    /**
     * Gets the value of the valuepair property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the valuepair property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVALUEPAIR().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VALUEPAIR }
     * 
     * 
     */
    public List<VALUEPAIR> getVALUEPAIR() {
        if (valuepair == null) {
            valuepair = new ArrayList<VALUEPAIR>();
        }
        return this.valuepair;
    }

    /**
     * Gets the value of the configreference property.
     * 
     * @return
     *     possible object is
     *     {@link CONFIGREFERENCE }
     *     
     */
    public CONFIGREFERENCE getCONFIGREFERENCE() {
        return configreference;
    }

    /**
     * Sets the value of the configreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link CONFIGREFERENCE }
     *     
     */
    public void setCONFIGREFERENCE(CONFIGREFERENCE value) {
        this.configreference = value;
    }

    /**
     * Gets the value of the sessioncomponent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sessioncomponent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSESSIONCOMPONENT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SESSIONCOMPONENT }
     * 
     * 
     */
    public List<SESSIONCOMPONENT> getSESSIONCOMPONENT() {
        if (sessioncomponent == null) {
            sessioncomponent = new ArrayList<SESSIONCOMPONENT>();
        }
        return this.sessioncomponent;
    }

    /**
     * Gets the value of the sessionextension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sessionextension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSESSIONEXTENSION().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SESSIONEXTENSION }
     * 
     * 
     */
    public List<SESSIONEXTENSION> getSESSIONEXTENSION() {
        if (sessionextension == null) {
            sessionextension = new ArrayList<SESSIONEXTENSION>();
        }
        return this.sessionextension;
    }

    /**
     * Gets the value of the resourcereferenceOrTRANSFORMRESOURCEREF property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resourcereferenceOrTRANSFORMRESOURCEREF property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRESOURCEREFERENCEOrTRANSFORMRESOURCEREF().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RESOURCEREFERENCE }
     * {@link TRANSFORMRESOURCEREF }
     * 
     * 
     */
    public List<Object> getRESOURCEREFERENCEOrTRANSFORMRESOURCEREF() {
        if (resourcereferenceOrTRANSFORMRESOURCEREF == null) {
            resourcereferenceOrTRANSFORMRESOURCEREF = new ArrayList<Object>();
        }
        return this.resourcereferenceOrTRANSFORMRESOURCEREF;
    }

}
