//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.10 at 11:47:16 PM IST 
//


package pc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "startoptions",
    "recurring"
})
@XmlRootElement(name = "TIMER")
public class TIMER {

    @XmlAttribute(name = "TIMERTYPE", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String timertype;
    @XmlElement(name = "STARTOPTIONS")
    protected STARTOPTIONS startoptions;
    @XmlElement(name = "RECURRING")
    protected RECURRING recurring;

    /**
     * Gets the value of the timertype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIMERTYPE() {
        return timertype;
    }

    /**
     * Sets the value of the timertype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIMERTYPE(String value) {
        this.timertype = value;
    }

    /**
     * Gets the value of the startoptions property.
     * 
     * @return
     *     possible object is
     *     {@link STARTOPTIONS }
     *     
     */
    public STARTOPTIONS getSTARTOPTIONS() {
        return startoptions;
    }

    /**
     * Sets the value of the startoptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link STARTOPTIONS }
     *     
     */
    public void setSTARTOPTIONS(STARTOPTIONS value) {
        this.startoptions = value;
    }

    /**
     * Gets the value of the recurring property.
     * 
     * @return
     *     possible object is
     *     {@link RECURRING }
     *     
     */
    public RECURRING getRECURRING() {
        return recurring;
    }

    /**
     * Sets the value of the recurring property.
     * 
     * @param value
     *     allowed object is
     *     {@link RECURRING }
     *     
     */
    public void setRECURRING(RECURRING value) {
        this.recurring = value;
    }

}
