//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.10 at 11:47:16 PM IST 
//


package pc;
import constant.PortType;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transformfieldattr"
})
@XmlRootElement(name = "TRANSFORMFIELD")
public class TRANSFORMFIELD implements Field{

    @XmlAttribute(name = "NAME", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "DESCRIPTION")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String description;
    @XmlAttribute(name = "DATATYPE", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String datatype;
    @XmlAttribute(name = "PORTTYPE", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String porttype;
    @XmlAttribute(name = "PRECISION", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String precision;
    @XmlAttribute(name = "SCALE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String scale;
    @XmlAttribute(name = "PICTURETEXT")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String picturetext;
    @XmlAttribute(name = "DEFAULTVALUE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String defaultvalue;
    @XmlAttribute(name = "EXPRESSION")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String expression;
    @XmlAttribute(name = "EXPRESSIONTYPE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String expressiontype;
    @XmlAttribute(name = "EXPRESSION_DESCRIPTION")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String expressiondescription;
    @XmlAttribute(name = "FIELDNUMBER")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String fieldnumber;
    @XmlAttribute(name = "REF_SOURCE_FIELD")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String refsourcefield;
    @XmlAttribute(name = "MAPPLETGROUP")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String mappletgroup;
    @XmlAttribute(name = "REF_FIELD")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String reffield;
    @XmlAttribute(name = "REF_TRANSFORMATION")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String reftransformation;
    @XmlAttribute(name = "REF_INSTANCETYPE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String refinstancetype;
    @XmlAttribute(name = "SEQUENCE_GENERATOR_VALUE")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String sequencegeneratorvalue;
    @XmlAttribute(name = "GROUP")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String group;
    @XmlAttribute(name = "OUTPUTGROUP")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String outputgroup;
    @XmlAttribute(name = "ISSORTKEY")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String issortkey;
    @XmlAttribute(name = "SORTDIRECTION")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String sortdirection;
    @XmlAttribute(name = "IGNORE_NULL_INPUTS")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String ignorenullinputs;
    @XmlAttribute(name = "IGNORE_IN_COMPARE")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String ignoreincompare;
    @XmlElement(name = "TRANSFORMFIELDATTR")
    protected List<TRANSFORMFIELDATTR> transformfieldattr;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCRIPTION() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCRIPTION(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the datatype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDATATYPE() {
        return datatype;
    }

    /**
     * Sets the value of the datatype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDATATYPE(String value) {
        this.datatype = value;
    }

    /**
     * Gets the value of the porttype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPORTTYPE() {

        return porttype;
    }

    /**
     * Sets the value of the porttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPORTTYPE(String value) {
        this.porttype = value;
    }

    /**
     * Gets the value of the precision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRECISION() {
        return precision;
    }

    /**
     * Sets the value of the precision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRECISION(String value) {
        this.precision = value;
    }

    /**
     * Gets the value of the scale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSCALE() {
        return scale;
    }

    /**
     * Sets the value of the scale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSCALE(String value) {
        this.scale = value;
    }

    /**
     * Gets the value of the picturetext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPICTURETEXT() {
        return picturetext;
    }

    /**
     * Sets the value of the picturetext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPICTURETEXT(String value) {
        this.picturetext = value;
    }

    /**
     * Gets the value of the defaultvalue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDEFAULTVALUE() {
        return defaultvalue;
    }

    /**
     * Sets the value of the defaultvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDEFAULTVALUE(String value) {
        this.defaultvalue = value;
    }

    /**
     * Gets the value of the expression property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXPRESSION() {
        return expression;
    }

    /**
     * Sets the value of the expression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXPRESSION(String value) {
        this.expression = value;
    }

    /**
     * Gets the value of the expressiontype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXPRESSIONTYPE() {
        return expressiontype;
    }

    /**
     * Sets the value of the expressiontype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXPRESSIONTYPE(String value) {
        this.expressiontype = value;
    }

    /**
     * Gets the value of the expressiondescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXPRESSIONDESCRIPTION() {
        return expressiondescription;
    }

    /**
     * Sets the value of the expressiondescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXPRESSIONDESCRIPTION(String value) {
        this.expressiondescription = value;
    }

    /**
     * Gets the value of the fieldnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIELDNUMBER() {
        return fieldnumber;
    }

    /**
     * Sets the value of the fieldnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIELDNUMBER(String value) {
        this.fieldnumber = value;
    }

    /**
     * Gets the value of the refsourcefield property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREFSOURCEFIELD() {
        return refsourcefield;
    }

    /**
     * Sets the value of the refsourcefield property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREFSOURCEFIELD(String value) {
        this.refsourcefield = value;
    }

    /**
     * Gets the value of the mappletgroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMAPPLETGROUP() {
        return mappletgroup;
    }

    /**
     * Sets the value of the mappletgroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMAPPLETGROUP(String value) {
        this.mappletgroup = value;
    }

    /**
     * Gets the value of the reffield property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREFFIELD() {
        return reffield;
    }

    /**
     * Sets the value of the reffield property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREFFIELD(String value) {
        this.reffield = value;
    }

    /**
     * Gets the value of the reftransformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREFTRANSFORMATION() {
        return reftransformation;
    }

    /**
     * Sets the value of the reftransformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREFTRANSFORMATION(String value) {
        this.reftransformation = value;
    }

    /**
     * Gets the value of the refinstancetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREFINSTANCETYPE() {
        return refinstancetype;
    }

    /**
     * Sets the value of the refinstancetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREFINSTANCETYPE(String value) {
        this.refinstancetype = value;
    }

    /**
     * Gets the value of the sequencegeneratorvalue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEQUENCEGENERATORVALUE() {
        return sequencegeneratorvalue;
    }

    /**
     * Sets the value of the sequencegeneratorvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEQUENCEGENERATORVALUE(String value) {
        this.sequencegeneratorvalue = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGROUP() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGROUP(String value) {
        this.group = value;
    }

    /**
     * Gets the value of the outputgroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOUTPUTGROUP() {
        return outputgroup;
    }

    /**
     * Sets the value of the outputgroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOUTPUTGROUP(String value) {
        this.outputgroup = value;
    }

    /**
     * Gets the value of the issortkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISSORTKEY() {
        return issortkey;
    }

    /**
     * Sets the value of the issortkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISSORTKEY(String value) {
        this.issortkey = value;
    }

    /**
     * Gets the value of the sortdirection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSORTDIRECTION() {
        return sortdirection;
    }

    /**
     * Sets the value of the sortdirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSORTDIRECTION(String value) {
        this.sortdirection = value;
    }

    /**
     * Gets the value of the ignorenullinputs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIGNORENULLINPUTS() {
        return ignorenullinputs;
    }

    /**
     * Sets the value of the ignorenullinputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIGNORENULLINPUTS(String value) {
        this.ignorenullinputs = value;
    }

    /**
     * Gets the value of the ignoreincompare property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIGNOREINCOMPARE() {
        return ignoreincompare;
    }

    /**
     * Sets the value of the ignoreincompare property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIGNOREINCOMPARE(String value) {
        this.ignoreincompare = value;
    }

    /**
     * Gets the value of the transformfieldattr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transformfieldattr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTRANSFORMFIELDATTR().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRANSFORMFIELDATTR }
     * 
     * 
     */
    public List<TRANSFORMFIELDATTR> getTRANSFORMFIELDATTR() {
        if (transformfieldattr == null) {
            transformfieldattr = new ArrayList<TRANSFORMFIELDATTR>();
        }
        return this.transformfieldattr;
    }

    public String getName() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public String getDataType() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public int getPrecision() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public int getScale() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void setName(String name) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void setDataType(String dataType) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void setPrecision(int precision) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void setScale(int scale) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public String getPortType() {
              if(PortType.isInputPort(PortType.valueOf(porttype))){
                  return PortType.INPUT.getPortType();
              }else{
                  return PortType.OUTPUT.getPortType();
              }
    }

    public void setPortType(String porttype) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

}
