//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.10 at 11:47:16 PM IST 
//


package pc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "scheduler",
    "task",
    "session",
    "worklet",
    "taskinstance",
    "workflowlink",
    "workflowvariable",
    "workflowevent",
    "attribute",
    "metadataextension",
    "conwfruninfo"
})
@XmlRootElement(name = "WORKFLOW")
public class WORKFLOW {

    @XmlAttribute(name = "NAME", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "DESCRIPTION")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String description;
    @XmlAttribute(name = "SERVERNAME")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String servername;
    @XmlAttribute(name = "SERVER_DOMAINNAME")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String serverdomainname;
    @XmlAttribute(name = "SUSPENSION_EMAIL")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String suspensionemail;
    @XmlAttribute(name = "SCHEDULERNAME")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String schedulername;
    @XmlAttribute(name = "REUSABLE_SCHEDULER")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String reusablescheduler;
    @XmlAttribute(name = "ISVALID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String isvalid;
    @XmlAttribute(name = "ISENABLED")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String isenabled;
    @XmlAttribute(name = "SUSPEND_ON_ERROR")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String suspendonerror;
    @XmlAttribute(name = "TASKS_MUST_RUN_ON_SERVER")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String tasksmustrunonserver;
    @XmlAttribute(name = "VERSIONNUMBER")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String versionnumber;
    @XmlAttribute(name = "ISSERVICE")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String isservice;
    @XmlAttribute(name = "ISRUNNABLESERVICE")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String isrunnableservice;
    @XmlAttribute(name = "SERVICELEVELNAME")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String servicelevelname;
    @XmlElement(name = "SCHEDULER")
    protected SCHEDULER scheduler;
    @XmlElement(name = "TASK")
    protected List<TASK> task;
    @XmlElement(name = "SESSION")
    protected List<SESSION> session;
    @XmlElement(name = "WORKLET")
    protected List<WORKLET> worklet;
    @XmlElement(name = "TASKINSTANCE")
    protected List<TASKINSTANCE> taskinstance;
    @XmlElement(name = "WORKFLOWLINK")
    protected List<WORKFLOWLINK> workflowlink;
    @XmlElement(name = "WORKFLOWVARIABLE")
    protected List<WORKFLOWVARIABLE> workflowvariable;
    @XmlElement(name = "WORKFLOWEVENT")
    protected List<WORKFLOWEVENT> workflowevent;
    @XmlElement(name = "ATTRIBUTE")
    protected List<ATTRIBUTE> attribute;
    @XmlElement(name = "METADATAEXTENSION")
    protected List<METADATAEXTENSION> metadataextension;
    @XmlElement(name = "CONWFRUNINFO")
    protected List<CONWFRUNINFO> conwfruninfo;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCRIPTION() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCRIPTION(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the servername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSERVERNAME() {
        return servername;
    }

    /**
     * Sets the value of the servername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSERVERNAME(String value) {
        this.servername = value;
    }

    /**
     * Gets the value of the serverdomainname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSERVERDOMAINNAME() {
        return serverdomainname;
    }

    /**
     * Sets the value of the serverdomainname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSERVERDOMAINNAME(String value) {
        this.serverdomainname = value;
    }

    /**
     * Gets the value of the suspensionemail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUSPENSIONEMAIL() {
        return suspensionemail;
    }

    /**
     * Sets the value of the suspensionemail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUSPENSIONEMAIL(String value) {
        this.suspensionemail = value;
    }

    /**
     * Gets the value of the schedulername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSCHEDULERNAME() {
        return schedulername;
    }

    /**
     * Sets the value of the schedulername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSCHEDULERNAME(String value) {
        this.schedulername = value;
    }

    /**
     * Gets the value of the reusablescheduler property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREUSABLESCHEDULER() {
        return reusablescheduler;
    }

    /**
     * Sets the value of the reusablescheduler property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREUSABLESCHEDULER(String value) {
        this.reusablescheduler = value;
    }

    /**
     * Gets the value of the isvalid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISVALID() {
        return isvalid;
    }

    /**
     * Sets the value of the isvalid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISVALID(String value) {
        this.isvalid = value;
    }

    /**
     * Gets the value of the isenabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISENABLED() {
        return isenabled;
    }

    /**
     * Sets the value of the isenabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISENABLED(String value) {
        this.isenabled = value;
    }

    /**
     * Gets the value of the suspendonerror property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUSPENDONERROR() {
        return suspendonerror;
    }

    /**
     * Sets the value of the suspendonerror property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUSPENDONERROR(String value) {
        this.suspendonerror = value;
    }

    /**
     * Gets the value of the tasksmustrunonserver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTASKSMUSTRUNONSERVER() {
        return tasksmustrunonserver;
    }

    /**
     * Sets the value of the tasksmustrunonserver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTASKSMUSTRUNONSERVER(String value) {
        this.tasksmustrunonserver = value;
    }

    /**
     * Gets the value of the versionnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVERSIONNUMBER() {
        return versionnumber;
    }

    /**
     * Sets the value of the versionnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVERSIONNUMBER(String value) {
        this.versionnumber = value;
    }

    /**
     * Gets the value of the isservice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISSERVICE() {
        return isservice;
    }

    /**
     * Sets the value of the isservice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISSERVICE(String value) {
        this.isservice = value;
    }

    /**
     * Gets the value of the isrunnableservice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISRUNNABLESERVICE() {
        return isrunnableservice;
    }

    /**
     * Sets the value of the isrunnableservice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISRUNNABLESERVICE(String value) {
        this.isrunnableservice = value;
    }

    /**
     * Gets the value of the servicelevelname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSERVICELEVELNAME() {
        return servicelevelname;
    }

    /**
     * Sets the value of the servicelevelname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSERVICELEVELNAME(String value) {
        this.servicelevelname = value;
    }

    /**
     * Gets the value of the scheduler property.
     * 
     * @return
     *     possible object is
     *     {@link SCHEDULER }
     *     
     */
    public SCHEDULER getSCHEDULER() {
        return scheduler;
    }

    /**
     * Sets the value of the scheduler property.
     * 
     * @param value
     *     allowed object is
     *     {@link SCHEDULER }
     *     
     */
    public void setSCHEDULER(SCHEDULER value) {
        this.scheduler = value;
    }

    /**
     * Gets the value of the task property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the task property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTASK().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TASK }
     * 
     * 
     */
    public List<TASK> getTASK() {
        if (task == null) {
            task = new ArrayList<TASK>();
        }
        return this.task;
    }

    /**
     * Gets the value of the session property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the session property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSESSION().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SESSION }
     * 
     * 
     */
    public List<SESSION> getSESSION() {
        if (session == null) {
            session = new ArrayList<SESSION>();
        }
        return this.session;
    }

    /**
     * Gets the value of the worklet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the worklet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWORKLET().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WORKLET }
     * 
     * 
     */
    public List<WORKLET> getWORKLET() {
        if (worklet == null) {
            worklet = new ArrayList<WORKLET>();
        }
        return this.worklet;
    }

    /**
     * Gets the value of the taskinstance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taskinstance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTASKINSTANCE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TASKINSTANCE }
     * 
     * 
     */
    public List<TASKINSTANCE> getTASKINSTANCE() {
        if (taskinstance == null) {
            taskinstance = new ArrayList<TASKINSTANCE>();
        }
        return this.taskinstance;
    }

    /**
     * Gets the value of the workflowlink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the workflowlink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWORKFLOWLINK().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WORKFLOWLINK }
     * 
     * 
     */
    public List<WORKFLOWLINK> getWORKFLOWLINK() {
        if (workflowlink == null) {
            workflowlink = new ArrayList<WORKFLOWLINK>();
        }
        return this.workflowlink;
    }

    /**
     * Gets the value of the workflowvariable property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the workflowvariable property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWORKFLOWVARIABLE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WORKFLOWVARIABLE }
     * 
     * 
     */
    public List<WORKFLOWVARIABLE> getWORKFLOWVARIABLE() {
        if (workflowvariable == null) {
            workflowvariable = new ArrayList<WORKFLOWVARIABLE>();
        }
        return this.workflowvariable;
    }

    /**
     * Gets the value of the workflowevent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the workflowevent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWORKFLOWEVENT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WORKFLOWEVENT }
     * 
     * 
     */
    public List<WORKFLOWEVENT> getWORKFLOWEVENT() {
        if (workflowevent == null) {
            workflowevent = new ArrayList<WORKFLOWEVENT>();
        }
        return this.workflowevent;
    }

    /**
     * Gets the value of the attribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getATTRIBUTE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ATTRIBUTE }
     * 
     * 
     */
    public List<ATTRIBUTE> getATTRIBUTE() {
        if (attribute == null) {
            attribute = new ArrayList<ATTRIBUTE>();
        }
        return this.attribute;
    }

    /**
     * Gets the value of the metadataextension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metadataextension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMETADATAEXTENSION().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link METADATAEXTENSION }
     * 
     * 
     */
    public List<METADATAEXTENSION> getMETADATAEXTENSION() {
        if (metadataextension == null) {
            metadataextension = new ArrayList<METADATAEXTENSION>();
        }
        return this.metadataextension;
    }

    /**
     * Gets the value of the conwfruninfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the conwfruninfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCONWFRUNINFO().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CONWFRUNINFO }
     * 
     * 
     */
    public List<CONWFRUNINFO> getCONWFRUNINFO() {
        if (conwfruninfo == null) {
            conwfruninfo = new ArrayList<CONWFRUNINFO>();
        }
        return this.conwfruninfo;
    }

}
