//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.10 at 11:47:16 PM IST 
//


package pc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "exprmacrodependency"
})
@XmlRootElement(name = "WORKFLOWLINK")
public class WORKFLOWLINK {

    @XmlAttribute(name = "FROMTASK", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String fromtask;
    @XmlAttribute(name = "TOTASK", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String totask;
    @XmlAttribute(name = "CONDITION")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String condition;
    @XmlElement(name = "EXPRMACRODEPENDENCY")
    protected List<EXPRMACRODEPENDENCY> exprmacrodependency;

    /**
     * Gets the value of the fromtask property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFROMTASK() {
        return fromtask;
    }

    /**
     * Sets the value of the fromtask property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFROMTASK(String value) {
        this.fromtask = value;
    }

    /**
     * Gets the value of the totask property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOTASK() {
        return totask;
    }

    /**
     * Sets the value of the totask property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOTASK(String value) {
        this.totask = value;
    }

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONDITION() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONDITION(String value) {
        this.condition = value;
    }

    /**
     * Gets the value of the exprmacrodependency property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exprmacrodependency property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEXPRMACRODEPENDENCY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EXPRMACRODEPENDENCY }
     * 
     * 
     */
    public List<EXPRMACRODEPENDENCY> getEXPRMACRODEPENDENCY() {
        if (exprmacrodependency == null) {
            exprmacrodependency = new ArrayList<EXPRMACRODEPENDENCY>();
        }
        return this.exprmacrodependency;
    }

}
